//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int court_id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public string type { get; set; }
        public decimal price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public string payment_method { get; set; }
        public Nullable<int> invoice_id { get; set; }
    
        public virtual court court { get; set; }
        public virtual customer customer { get; set; }
        public virtual invoice invoice { get; set; }
    }
}
