//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLySanCauLongEntities : DbContext
    {
        public QuanLySanCauLongEntities()
            : base("name=QuanLySanCauLongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<court> courts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<expens> expenses { get; set; }
        public virtual DbSet<invoice_details> invoice_details { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<mat_hang> mat_hang { get; set; }
        public virtual DbSet<nhap_kho> nhap_kho { get; set; }
        public virtual DbSet<price_rules> price_rules { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<ton_kho> ton_kho { get; set; }
        public virtual DbSet<work_schedule> work_schedule { get; set; }
    
        [DbFunction("QuanLySanCauLongEntities", "fn_xem_ton_kho_chi_tiet")]
        public virtual IQueryable<fn_xem_ton_kho_chi_tiet_Result> fn_xem_ton_kho_chi_tiet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_xem_ton_kho_chi_tiet_Result>("[QuanLySanCauLongEntities].[fn_xem_ton_kho_chi_tiet]()");
        }
    
        public virtual ObjectResult<sp_TinhNoChiTietKhachHang_Result> sp_TinhNoChiTietKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TinhNoChiTietKhachHang_Result>("sp_TinhNoChiTietKhachHang");
        }
    }
}
