//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ton_kho
    {
        public int item_id { get; set; }
        public Nullable<int> so_luong_ton { get; set; }
    
        public virtual mat_hang mat_hang { get; set; }
    }
}
