//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_schedule
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public System.DateTime work_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
