//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mat_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mat_hang()
        {
            this.invoice_details = new HashSet<invoice_details>();
            this.nhap_kho = new HashSet<nhap_kho>();
        }
    
        public int id { get; set; }
        public string ten_hang { get; set; }
        public decimal gia_ban { get; set; }
        public string don_vi_chinh { get; set; }
        public string don_vi_quy_doi { get; set; }
        public Nullable<int> so_luong_quy_doi { get; set; }
        public Nullable<decimal> gia_nhap { get; set; }
        public string loai { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string don_vi { get; set; }
        public string hinh_anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_details> invoice_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhap_kho> nhap_kho { get; set; }
        public virtual ton_kho ton_kho { get; set; }
    }
}
