//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhap_kho
    {
        public int id { get; set; }
        public int item_id { get; set; }
        public int so_luong { get; set; }
        public decimal gia_nhap { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string don_vi { get; set; }
    
        public virtual mat_hang mat_hang { get; set; }
    }
}
