//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class price_rules
    {
        public int id { get; set; }
        public Nullable<int> day_of_week { get; set; }
        public Nullable<int> start_hour { get; set; }
        public Nullable<int> end_hour { get; set; }
        public string type { get; set; }
        public Nullable<decimal> price_per_hour { get; set; }
    }
}
