//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLySanCauLongdbEntities : DbContext
    {
        public QuanLySanCauLongdbEntities()
            : base("name=QuanLySanCauLongdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookings> bookings { get; set; }
        public virtual DbSet<courts> courts { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<price_rules> price_rules { get; set; }
        public virtual DbSet<salary> salary { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<work_schedule> work_schedule { get; set; }
        public virtual DbSet<invoice_details> invoice_details { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
    }
}
