//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public Nullable<int> total_shift { get; set; }
        public Nullable<decimal> total_hours { get; set; }
        public decimal base_salary { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
