//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string item_name { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual customers customers { get; set; }
    }
}
